version: "3"
services:
  balloonwatch:
    restart: unless-stopped
    container_name: balloonwatch
    image: balloonwatch
    depends_on:
      - mongodb
    networks:
      - bw_network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/

  mongodb:
    restart: unless-stopped
    container_name: mongodb
    image: mongo
    volumes:
      - bw_mongo_data:/data/db
    networks:
      - bw_network


networks:
  bw_network:
volumes:
  bw_mongo_data: